import { useEffect, useState } from "react";
import styled from "styled-components";

const DISCLAIMER_KEY = "portfolioAnalyzer_disclaimerAcknowledged";

export default function DisclaimerModal() {
  const [isOpen, setIsOpen] = useState(false);

  useEffect(() => {
    const acknowledged = localStorage.getItem(DISCLAIMER_KEY);
    if (!acknowledged) {
      setIsOpen(true);
    }
  }, []);

  const handleAcknowledge = () => {
    localStorage.setItem(DISCLAIMER_KEY, "true");
    setIsOpen(false);
  };

  if (!isOpen) return null;

  return (
    <Overlay role="dialog" aria-modal="true" aria-labelledby="disclaimer-title">
      <ModalContainer>
        <Header>
          <Icon aria-hidden="true">⚠️</Icon>
          <Title id="disclaimer-title">Important Disclaimer</Title>
        </Header>

        <Content>
          <Section>
            <SectionTitle>Educational Tool Only</SectionTitle>
            <Text>
              This application is designed for <strong>educational and analytical purposes only</strong>.
              It is NOT a source of investment advice, financial recommendations, or trading signals.
            </Text>
          </Section>

          <Section>
            <SectionTitle>Not Investment Advice</SectionTitle>
            <Text>
              All portfolio signals (underweight, balanced, overweight) are <strong>informational indicators</strong>
              based on portfolio metrics like diversification and concentration. They do NOT constitute
              recommendations to buy, sell, or hold any securities.
            </Text>
          </Section>

          <Section>
            <SectionTitle>AI-Generated Content</SectionTitle>
            <Text>
              Portfolio explanations are generated by AI and may contain errors or inaccuracies.
              Always verify information independently and consult qualified financial professionals
              before making investment decisions.
            </Text>
          </Section>

          <Section>
            <SectionTitle>Your Responsibility</SectionTitle>
            <Text>
              By using this tool, you acknowledge that:
            </Text>
            <List>
              <li>You are solely responsible for your investment decisions</li>
              <li>Past performance does not guarantee future results</li>
              <li>All investments carry risk, including loss of principal</li>
              <li>You should consult a licensed financial advisor for personalized advice</li>
            </List>
          </Section>
        </Content>

        <Footer>
          <AcknowledgeButton onClick={handleAcknowledge}>
            I Understand - Continue to Tool
          </AcknowledgeButton>
        </Footer>
      </ModalContainer>
    </Overlay>
  );
}

/* ========== Styles ========== */

const Overlay = styled.div`
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.85);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 9999;
  padding: ${({ theme }) => theme.spacing.md};
  backdrop-filter: blur(4px);
`;

const ModalContainer = styled.div`
  background: linear-gradient(135deg, #2d1b4e 0%, #3d2b5e 100%);
  border: 3px solid rgba(255, 51, 102, 0.5);
  border-radius: ${({ theme }) => theme.radius.lg};
  max-width: 650px;
  width: 100%;
  max-height: 90vh;
  overflow-y: auto;
  box-shadow: 0 10px 40px rgba(255, 51, 102, 0.4);
`;

const Header = styled.div`
  padding: ${({ theme }) => theme.spacing.lg};
  border-bottom: 2px solid ${({ theme }) => theme.semantic.high.border};
  background: ${({ theme }) => theme.semantic.high.bg};
  display: flex;
  align-items: center;
  gap: ${({ theme }) => theme.spacing.sm};
  border-radius: ${({ theme }) => theme.radius.lg} ${({ theme }) => theme.radius.lg} 0 0;
`;

const Icon = styled.span`
  font-size: 1.75rem;
`;

const Title = styled.h2`
  font-size: ${({ theme }) => theme.typography.heading};
  font-weight: ${({ theme }) => theme.fontWeight.bold};
  color: ${({ theme }) => theme.semantic.high.text};
  margin: 0;
`;

const Content = styled.div`
  padding: ${({ theme }) => theme.spacing.lg};
`;

const Section = styled.div`
  margin-bottom: ${({ theme }) => theme.spacing.lg};

  &:last-child {
    margin-bottom: 0;
  }
`;

const SectionTitle = styled.h3`
  font-size: ${({ theme }) => theme.typography.label};
  font-weight: ${({ theme }) => theme.fontWeight.semibold};
  color: ${({ theme }) => theme.colors.accent};
  margin-bottom: ${({ theme }) => theme.spacing.xs};
`;

const Text = styled.p`
  font-size: ${({ theme }) => theme.typography.body};
  color: ${({ theme }) => theme.colors.textPrimary};
  line-height: 1.6;
  margin: 0;

  strong {
    color: ${({ theme }) => theme.colors.accent};
    font-weight: ${({ theme }) => theme.fontWeight.semibold};
  }
`;

const List = styled.ul`
  margin: ${({ theme }) => theme.spacing.sm} 0 0 ${({ theme }) => theme.spacing.lg};
  padding: 0;

  li {
    font-size: ${({ theme }) => theme.typography.body};
    color: ${({ theme }) => theme.colors.textPrimary};
    line-height: 1.6;
    margin-bottom: ${({ theme }) => theme.spacing.xs};
  }
`;

const Footer = styled.div`
  padding: ${({ theme }) => theme.spacing.xl};
  border-top: 2px solid rgba(255, 51, 102, 0.4);
  background: linear-gradient(135deg, #3d2b5e 0%, #4d3b6e 100%);
  border-radius: 0 0 ${({ theme }) => theme.radius.lg} ${({ theme }) => theme.radius.lg};
`;

const AcknowledgeButton = styled.button`
  width: 100%;
  padding: ${({ theme }) => theme.spacing.md};
  border-radius: ${({ theme }) => theme.radius.lg};
  border: none;
  background: linear-gradient(135deg, #ff3366 0%, #ff5588 100%);
  color: #ffffff;
  font-size: ${({ theme }) => theme.typography.label};
  font-weight: ${({ theme }) => theme.fontWeight.bold};
  cursor: pointer;
  transition: all ${({ theme }) => theme.motion.normal};
  box-shadow: 0 4px 20px rgba(255, 51, 102, 0.4);

  &:hover {
    background: linear-gradient(135deg, #ff5588 0%, #ff77aa 100%);
    transform: translateY(-2px);
    box-shadow: 0 6px 25px rgba(255, 51, 102, 0.6);
  }

  &:focus-visible {
    outline: 3px solid ${({ theme }) => theme.colors.focus};
    outline-offset: 2px;
  }

  &:active {
    transform: translateY(0);
    box-shadow: 0 4px 20px rgba(255, 51, 102, 0.4);
  }
`;
