const NO_EXPLANATION = "No explanation available.";
const MAX_RETRIES = 3;

async function callGeminiAPI(score, metrics) {
  const response = await fetch(
    "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions",
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        // IMPORTANT: Bearer token, not x-api-key
        Authorization: `Bearer ${process.env.GEMINI_API_KEY}`,
      },
      body: JSON.stringify({
        // ✅ These models work ONLY on the OpenAI-compatible endpoint
        model: "gemini-2.0-flash",
        messages: [
          {
            role: "system",
            content:
              "You are an explainability assistant for a regulated fintech product. No investment advice.",
          },
          {
            role: "user",
            content: `
ROLE:
You are an explainability and risk-disclosure assistant for a SEBI-conscious Indian fintech analytics product.
You provide descriptive analysis only. You are NOT an investment advisor.

NON-NEGOTIABLE CONSTRAINTS:
- Do NOT provide investment advice
- Do NOT suggest buy, sell, or hold actions
- Do NOT recommend position sizing or timing
- Do NOT predict future prices or returns
- Do NOT use persuasive or directive language
- Use neutral, factual, and analytical tone only
- Base explanations strictly on provided data
- If data is insufficient, say so explicitly
- Always acknowledge uncertainty and limitations

ANALYSIS CONTEXT:
The following score and metrics are generated by a deterministic analytics system.
They are indicators, not predictions or recommendations.

SCORE (0–100):
${score}

INPUT METRICS (may be incomplete or noisy):
${JSON.stringify(metrics, null, 2)}

YOUR TASK:
Explain what this score and these metrics indicate at a high level.
Focus on *drivers, relationships, and signals*, not outcomes or actions.

RESPONSE FORMAT (STRICT — follow exactly):

SUMMARY:
(1 short paragraph explaining what the score broadly reflects, without advice or forecasts)

KEY DRIVERS:
- Describe the first major factor influencing the score
- Describe the second major factor influencing the score
- Describe the third major factor influencing the score
(Use neutral descriptions, not judgments)

LIMITATIONS & ASSUMPTIONS:
(1 short paragraph stating data gaps, model limitations, or assumptions made)

UNCERTAINTY:
(1 short paragraph clearly explaining why outcomes may differ and why this analysis should not be relied on alone)

FINAL SAFETY NOTE:
(This analysis is informational and exploratory in nature. It does not constitute investment advice or a recommendation of any kind.)
`,
          },
        ],
        temperature: 0.4,
      }),
    },
  );

  const data = await response.json();
  return data?.choices?.[0]?.message?.content || null;
}

function isValidExplanation(text) {
  return text && text.trim() !== "" && text !== NO_EXPLANATION;
}

export default async function handler(req, res) {
  try {
    res.setHeader("Content-Type", "application/json");

    if (req.method !== "POST") {
      return res.status(405).json({ error: "Method not allowed" });
    }

    const { score, metrics } = req.body || {};
    if (!score || !metrics) {
      return res.status(400).json({ error: "Invalid payload" });
    }

    // Retry logic: keep trying until we get a valid explanation or hit max retries
    let explanation = null;
    let attempts = 0;

    while (attempts < MAX_RETRIES) {
      attempts++;
      const result = await callGeminiAPI(score, metrics);

      if (isValidExplanation(result)) {
        explanation = result;
        break;
      }

      // 🔍 Debug log for failed attempts
      console.log(
        `Gemini API attempt ${attempts} returned empty/invalid response, retrying...`,
      );
    }

    // If all retries failed, return the fallback message
    if (!explanation) {
      console.log(`All ${MAX_RETRIES} Gemini API attempts failed`);
      return res.status(200).json({ explanation: NO_EXPLANATION });
    }

    return res.status(200).json({ explanation });
  } catch (err) {
    console.error("Explain API error:", err);
    return res.status(500).json({ error: "AI generation failed" });
  }
}
